package com.matteopaciolla.prbe.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.util.List;

@Schema(name = "Move", description = "A single move recorded in a match, including its generated events and game-state context.")
@Data
@JsonInclude(JsonInclude.Include.NON_NULL)
public class MoveDto {

    @Schema(description = "Persistent database identifier of the move.", example = "125")
    private Long id;

    @Schema(description = "Timestamp when the move was recorded.", example = "2026-09-28T10:35:00Z")
    private String createdAt;

    @Schema(description = "Version of the game engine used to execute this move.", example = "1.0.0")
    private String libVersion;

    @Schema(description = "Configuration id used for the match execution context.", example = "1")
    private Integer configurationId;

    @Schema(description = "Match code to which the move belongs.", example = "ABC123")
    private String matchKeyCode;

    @Schema(description = "Sequential move index within the match timeline.", example = "14")
    private Integer timeIndex;

    @Schema(description = "Username of the player who was active when the move was executed.", example = "alice")
    private String activePlayerUsername;

    @Schema(description = "Index of the active player.", example = "0")
    private Integer activePlayerIndex;

    @Schema(description = "Username of the player who was running the move", example = "alice")
    private String runningPlayerUsername;

    @Schema(description = "Index of the running player.", example = "0")
    private Integer runningPlayerIndex;

    @Schema(description = "Enum name of the action executed by the move.", example = "DISCOVER")
    private String moveName;

    @Schema(description = "Primary parameter index used by the action, when required.", example = "0")
    private Integer parameterIndex;

    @Schema(description = "Target player index used by the action, when required.", example = "-1")
    private Integer pickPlayerIndex;

    @Schema(description = "Minion list chosen for expedition commit moves.", example = "[\"CAPTAIN\", \"CAPTAIN\", \"SETTLER\"]")
    private List<String> expeditionEmployeesList;

    @Schema(description = "Freeform textual notes produced by the engine for the move execution.", example = "Ship discovered")
    private String notes;

    @Schema(description = "Main event generated by the move, if any.")
    private EventDto mainEvent;

    @Schema(description = "Secondary events generated by the move, if any.")
    private List<EventDto> sideEvents;

    @Schema(description = "Current phase name at the moment the move was recorded.", example = "TRADE_HIRE_MAIN")
    private String currentPhaseName; // Optional, used for contextual information
}
