package com.matteopaciolla.prbe.constants;

import java.util.List;

public final class FakeNames {

    public static final List<String> FIRST_NAMES = List.of(
            "Sir James",
            "Duke Anthony",
            "Lord Percival",
            "Baron Theodore",
            "Captain Reginald",
            "Sir Edmund",
            "Duke Alistair",
            "Lord Benedict",
            "Baron Frederick",
            "Captain Rupert",
            "Sir Archibald",
            "Duke Clarence",
            "Lord Montgomery",
            "Baron Augustus",
            "Captain Barnaby",
            "Sir Winston",
            "Duke Maximilian",
            "Lord Cornelius",
            "Baron Leopold",
            "Captain Horatio",
            "Sir Geoffrey",
            "Duke Sebastian",
            "Lord Bartholomew",
            "Baron Thaddeus",
            "Captain Percival",
            "Sir Rupert",
            "Duke Frederick",
            "Lord Archibald",
            "Baron Lionel",
            "Captain Horace",
            "Sir Reginald",
            "Duke Oliver",
            "Lord Theodore",
            "Baron Crispin",
            "Captain Alistair",
            "Sir Bartholomew",
            "Duke Percival",
            "Lord Augustus",
            "Baron Edmund",
            "Captain Benedict",
            "Sir Cornelius",
            "Duke Rupert",
            "Lord Leopold",
            "Baron Winston",
            "Captain Montgomery",
            "Sir Horatio",
            "Duke Archibald",
            "Lord Frederick",
            "Baron Sebastian",
            "Captain Theodore",
            "Sir Maximilian",
            "Duke Barnaby",
            "Lord Rupert",
            "Baron Percival",
            "Captain Augustus",
            "Sir Lionel",
            "Duke Winston",
            "Lord Alistair",
            "Baron Bartholomew",
            "Captain Crispin"
    );

    public static final List<String> LAST_NAMES = List.of(
            "Norrington",
            "Wallace",
            "Ashford",
            "Wellington",
            "Blackwood",
            "Fairfax",
            "Montgomery",
            "Harrington",
            "Kensington",
            "Thornfield",
            "Pembroke",
            "Whitmore",
            "Fitzgerald",
            "Chamberlain",
            "Hollingsworth",
            "Pemberton",
            "Bramwell",
            "Ainsworth",
            "Kingsley",
            "Everett",
            "Whitaker",
            "Langley",
            "Cavendish",
            "Rutherford",
            "Davenport",
            "Hawthorne",
            "Windsor",
            "Carmichael",
            "Beaumont",
            "Middleton",
            "Worthington",
            "Bellington",
            "Montague",
            "Fothergill",
            "Bexley",
            "Wainwright",
            "Huntington",
            "Trelawney",
            "Ravenscroft",
            "Fairchild",
            "Hargreaves",
            "Ashcombe",
            "Underwood",
            "Greystone",
            "Pritchard",
            "Cumberland",
            "Merriweather",
            "Tavistock",
            "Brambleton",
            "Pennyworth",
            "Appleton",
            "Hatherleigh",
            "Wetherby",
            "Bumblewick",
            "Thistledown",
            "Cumberbatch",
            "Farnsworth",
            "Puddifoot",
            "Weatherby",
            "Thornbury"
    );

    private FakeNames() {}
}
