#### Spring Boot Configuration ####
spring.jpa.open-in-view=false
# needed for avoiding the error: AsyncRequestTimeoutException when using Long Polling
spring.mvc.async.request-timeout=-1
# /api-docs endpoint custom path
springdoc.api-docs.path=/api-docs
###### Database Configuration ######
#spring.datasource.url=jdbc:postgresql://mightyshaman.com:5432/prdb
#spring.datasource.username=user
#spring.datasource.password=pass
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
###### Database Configuration ######

###### Variables from Maven pom.xml ######
portroyal.lib.version=@prlib.version@
###### Variables from Maven pom.xml ######
#### Spring Boot Configuration ####

#### Schema Generation (just for development) ####
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=drop-and-create
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=create-schema.sql
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.drop-target=drop-schema.sql
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#### Schema Generation (just for development) ####

#### HikariCP Connection Pool ####
spring.datasource.hikari.max-lifetime=580000
#spring.datasource.hikari.idle-timeout=300000
#spring.datasource.hikari.connection-timeout=30000
#spring.datasource.hikari.maximum-pool-size=10

#spring.datasource.test-on-borrow=true
#spring.datasource.validation-query=SELECT 1

#spring.datasource.hikari.connection-test-query=SELECT 1
#spring.datasource.hikari.keepalive-time=240000
#### HikariCP Connection Pool ####

#### Logging with Spring Boot Actuator ####
#management.endpoints.web.exposure.include=*
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.boot.actuate=DEBUG
#### Logging with Spring Boot Actuator ####

#### Logging with Logbook ####
logbook.filter.enabled=true
logbook.format.style=default
logging.level.org.zalando.logbook=TRACE
#### Logging with Logbook ####

#### Common Properties ####
server.port=8080

#### Custom Properties ####
be_app.baseurl=prbe.mightyshaman.com
be_app.user.telegram_unification.enabled=true
be_app.user.telegram_unification.max_retries=3
be_app.cache.match.seconds-to-expire=60
