package com.matteopaciolla.portroyal.facades;

import com.matteopaciolla.portroyal.exceptions.IOGameException;
import com.matteopaciolla.portroyal.core.enums.MoveAction;
import com.matteopaciolla.portroyal.core.MoveRecord;
import com.matteopaciolla.portroyal.core.cards.enums.ExpeditionEmployee;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

public class IOFacadeTest {

    @Test
    public void testSaveMovesToCSV() throws IOGameException {
        List<MoveRecord> moves = List.of(
                new MoveRecord(0,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(1,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(2,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(3,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(4,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(5,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(6,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(7,1, MoveAction.FINISH_DISCOVER, null, null, null),
                new MoveRecord(8,1, MoveAction.TRADE_HIRE, 1, -1, null, null, null),
                new MoveRecord(9,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(10,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(11,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(12,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(13,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(14,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(15,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(16,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(17,2, MoveAction.FINISH_DISCOVER, null, null, null),
                new MoveRecord(18,2, MoveAction.TRADE_HIRE, 5, -1, null, null, null),
                new MoveRecord(19,0, MoveAction.END_TURN, -1, -1, null, null, null),
                new MoveRecord(20,1, MoveAction.TRADE_HIRE, 0, -1, null, null, null),
                new MoveRecord(21,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(22,0, MoveAction.FINISH_DISCOVER, null, null, null),
                new MoveRecord(23,0, MoveAction.TRADE_HIRE, 0, -1, null, null, null),
                new MoveRecord(24,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(25,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(26,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(27,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(28,1, MoveAction.FINISH_DISCOVER, null, null, null),
                new MoveRecord(29,1, MoveAction.TRADE_HIRE, 1, -1, null, null, null),
                new MoveRecord(30,0, MoveAction.TRADE_HIRE, 1, -1, null, null, null),
                new MoveRecord(31,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(32,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(33,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(34,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(35,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(36,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(37,2, MoveAction.FINISH_DISCOVER, null, null, null),
                new MoveRecord(38,2, MoveAction.TRADE_HIRE, 4, -1, null, null, null),
                new MoveRecord(39,0, MoveAction.TRADE_HIRE, 0, -1, null, null, null),
                new MoveRecord(40,1, MoveAction.END_TURN, -1, -1, null, null, null),
                new MoveRecord(41,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(42,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(43,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(44,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(45,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(46,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(47,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(48,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(49,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(50,0, MoveAction.FINISH_DISCOVER, null, null, null),
                new MoveRecord(51,0, MoveAction.TRADE_HIRE, 8, -1, null, null, null),
                new MoveRecord(52,1, MoveAction.TRADE_HIRE, 3, -1, null, null, null),
                new MoveRecord(53,2, MoveAction.TRADE_HIRE, 0, -1, null, null, null),
                new MoveRecord(54,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(55,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(56,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(57,1, MoveAction.FINISH_DISCOVER, null, null, null),
                new MoveRecord(58,1, MoveAction.TRADE_HIRE, 2, -1, null, null, null),
                new MoveRecord(59,0, MoveAction.END_TURN, null, null, null),
                new MoveRecord(60,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(61,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(62,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(63,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(64,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(65,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(66,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(67,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(68,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(69,2, MoveAction.REPEL, null, null, null),
                new MoveRecord(70,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(71,2, MoveAction.REPEL, null, null, null),
                new MoveRecord(72,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(73,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(74,2, MoveAction.FINISH_DISCOVER, null, null, null),
                new MoveRecord(75,2, MoveAction.TRADE_HIRE, 9, -1, null, null, null),
                new MoveRecord(76,0, MoveAction.END_TURN, -1, -1, null, null, null),
                new MoveRecord(77,1, MoveAction.END_TURN, -1, -1, null, null, null),
                new MoveRecord(78,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(79,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(80,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(81,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(82,0, MoveAction.FINISH_DISCOVER, null, null, null),
                new MoveRecord(83,0, MoveAction.TRADE_HIRE, 2, -1, null, null, null),
                new MoveRecord(84,1, MoveAction.TRADE_HIRE, 1, -1, null, null, null),
                new MoveRecord(85,2, MoveAction.END_TURN, -1, -1, null, null, null),
                new MoveRecord(86,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(87,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(88,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(89,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(90,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(91,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(92,1, MoveAction.FINISH_DISCOVER, null, null, null),
                new MoveRecord(93,1, MoveAction.TRADE_HIRE, 2, -1, null, null, null),
                new MoveRecord(94,1, MoveAction.TRADE_HIRE, 2, -1, null, null, null),
                new MoveRecord(95,2, MoveAction.TRADE_HIRE, 2, -1, null, null, null),
                new MoveRecord(96,0, MoveAction.END_TURN, -1, -1, null, null, null),
                new MoveRecord(97,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(98,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(99,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(100,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(101,2, MoveAction.REPEL, -1, -1, null, null, null),
                new MoveRecord(102,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(103,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(104,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(105,2, MoveAction.REPEL, -1, -1, null, null, null),
                new MoveRecord(106,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(107,2, MoveAction.REPEL, -1, -1, null, null, null),
                new MoveRecord(108,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(109,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(110,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(111,2, MoveAction.FINISH_DISCOVER, null, null, null),
                new MoveRecord(112,2, MoveAction.TRADE_HIRE, 7, -1, null, null, null),
                new MoveRecord(113,0, MoveAction.TRADE_HIRE, 2, -1, null, null, null),
                new MoveRecord(114,1, MoveAction.TRADE_HIRE, 0, -1, null, null, null),
                new MoveRecord(115,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(116,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(117,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(118,0, MoveAction.FINISH_DISCOVER, null, null, null),
                new MoveRecord(119,0, MoveAction.TRADE_HIRE, 2, -1, null, null, null),
                new MoveRecord(120,1, MoveAction.END_TURN, -1, -1, null, null, null),
                new MoveRecord(121,2, MoveAction.END_TURN, -1, -1, null, null, null),
                new MoveRecord(122,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(123,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(124,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(125,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(126,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(127,1, MoveAction.FINISH_DISCOVER, null, null, null),
                new MoveRecord(128,1, MoveAction.TRADE_HIRE, 4, -1, null, null, null),
                new MoveRecord(129,2, MoveAction.TRADE_HIRE, 2, -1, null, null, null),
                new MoveRecord(130,0, MoveAction.END_TURN, -1, -1, null, null, null),
                new MoveRecord(131,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(132,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(133,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(134,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(135,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(136,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(137,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(138,2, MoveAction.REPEL, -1, -1, null, null, null),
                new MoveRecord(139,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(140,2, MoveAction.FINISH_DISCOVER, null, null, null),
                new MoveRecord(141,2, MoveAction.TRADE_HIRE, 4, -1, null, null, null),
                new MoveRecord(142,0, MoveAction.TRADE_HIRE, 1, -1, null, null, null),
                new MoveRecord(143,1, MoveAction.TRADE_HIRE, 3, -1, null, null, null),
                new MoveRecord(144,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(145,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(146,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(147,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(148,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(149,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(150,0, MoveAction.FINISH_DISCOVER, null, null, null),
                new MoveRecord(151,0, MoveAction.TRADE_HIRE, 5, -1, null, null, null),
                new MoveRecord(152,1, MoveAction.END_TURN, -1, -1, null, null, null),
                new MoveRecord(153,2, MoveAction.END_TURN, -1, -1, null, null, null),
                new MoveRecord(154,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(155,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(156,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(157,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(158,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(159,1, MoveAction.FINISH_DISCOVER, null, null, null),
                new MoveRecord(160,1, MoveAction.TRADE_HIRE, 2, -1, null, null, null),
                new MoveRecord(161,1, MoveAction.TRADE_HIRE, 2, -1, null, null, null),
                new MoveRecord(162,0, MoveAction.TRADE_HIRE, 1, -1, null, null, null),
                new MoveRecord(163,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(164,2, MoveAction.REPEL, -1, -1, null, null, null),
                new MoveRecord(165,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(166,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(167,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(168,2, MoveAction.FINISH_DISCOVER, null, null, null),
                new MoveRecord(169,2, MoveAction.TRADE_HIRE, 2, -1, null, null, null),
                new MoveRecord(170,1, MoveAction.TRADE_HIRE, 0, -1, null, null, null),
                new MoveRecord(171,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(172,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(173,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(174,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(175,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(176,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(177,0, MoveAction.FINISH_DISCOVER, null, null, null),
                new MoveRecord(178,0, MoveAction.TRADE_HIRE, 0, -1, null, null, null),
                new MoveRecord(179,1, MoveAction.TRADE_HIRE, 4, -1, null, null, null),
                new MoveRecord(180,2, MoveAction.TRADE_HIRE, 1, -1, null, null, null),
                new MoveRecord(181,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(182,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(183,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(184,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(185,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(186,1, MoveAction.FINISH_DISCOVER, null, null, null),
                new MoveRecord(187,1, MoveAction.TRADE_HIRE, 0, -1, null, null, null),
                new MoveRecord(188,1, MoveAction.TRADE_HIRE, 0, -1, null, null, null),
                new MoveRecord(189,2, MoveAction.TRADE_HIRE, 1, -1, null, null, null),
                new MoveRecord(190,0, MoveAction.END_TURN, -1, -1, null, null, null),
                new MoveRecord(191,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(192,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(193,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(194,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(195,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(196,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(197,2, MoveAction.FINISH_DISCOVER, null, null, null),
                new MoveRecord(198,2, MoveAction.TRADE_HIRE, 3, -1, null, null, null),
                new MoveRecord(199,0, MoveAction.TRADE_HIRE, 1, -1, null, null, null),
                new MoveRecord(200,1, MoveAction.TRADE_HIRE, 3, -1, null, null, null),
                new MoveRecord(201,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(202,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(203,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(204,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(205,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(206,2, MoveAction.REPEL, -1, -1, null, null, null),
                new MoveRecord(207,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(208,2, MoveAction.REPEL, -1, -1, null, null, null),
                new MoveRecord(209,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(210,2, MoveAction.REPEL, -1, -1, null, null, null),
                new MoveRecord(211,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(212,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(213,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(214,2, MoveAction.REPEL, -1, -1, null, null, null),
                new MoveRecord(215,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(216,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(217,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(218,2, MoveAction.REPEL, -1, -1, null, null, null),
                new MoveRecord(219,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(220,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(221,2, MoveAction.FINISH_DISCOVER, null, null, null),
                new MoveRecord(222,2, MoveAction.TRADE_HIRE, 3, -1, null, null, null),
                new MoveRecord(223,0, MoveAction.TRADE_HIRE, 3, -1, null, null, null),
                new MoveRecord(224,1, MoveAction.TRADE_HIRE, 2, -1, null, null, null),
                new MoveRecord(225,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(226,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(227,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(228,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(229,0, MoveAction.FINISH_DISCOVER, null, null, null),
                new MoveRecord(230,0, MoveAction.TRADE_HIRE, 0, -1, null, null, null),
                new MoveRecord(231,1, MoveAction.TRADE_HIRE, 0, -1, null, null, null),
                new MoveRecord(232,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(233,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(234,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(235,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(236,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(237,1, MoveAction.FINISH_DISCOVER, null, null, null),
                new MoveRecord(238,1, MoveAction.TRADE_HIRE, 1, -1, null, null, null),
                new MoveRecord(239,1, MoveAction.TRADE_HIRE, 1, -1, null, null, null),
                new MoveRecord(240,2, MoveAction.TRADE_HIRE, 2, -1, null, null, null),
                new MoveRecord(241,0, MoveAction.TRADE_HIRE, 1, -1, null, null, null),
                new MoveRecord(242,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(243,2, MoveAction.REPEL, -1, -1, null, null, null),
                new MoveRecord(244,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(245,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(246,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(247,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(248,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(249,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(250,2, MoveAction.REPEL, -1, -1, null, null, null),
                new MoveRecord(251,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(252,2, MoveAction.REPEL, -1, -1, null, null, null),
                new MoveRecord(253,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(254,2, MoveAction.FINISH_DISCOVER, null, null, null),
                new MoveRecord(255,2, MoveAction.TRADE_HIRE, 0, -1, null, null, null),
                new MoveRecord(256,0, MoveAction.TRADE_HIRE, 2, -1, null, null, null),
                new MoveRecord(257,1, MoveAction.TRADE_HIRE, 1, -1, null, null, null),
                new MoveRecord(258,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(259,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(260,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(261,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(262,0, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(263,0, MoveAction.FINISH_DISCOVER, null, null, null),
                new MoveRecord(264,0, MoveAction.TRADE_HIRE, 2, -1, null, null, null),
                new MoveRecord(265,1, MoveAction.TRADE_HIRE, 1, -1, null, null, null),
                new MoveRecord(266,2, MoveAction.TRADE_HIRE, 2, -1, null, null, null),
                new MoveRecord(267,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(268,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(269,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(270,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(271,1, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(272,1, MoveAction.FINISH_DISCOVER, null, null, null),
                new MoveRecord(273,1, MoveAction.TRADE_HIRE, 4, -1, null, null, null),
                new MoveRecord(274,1, MoveAction.TRADE_HIRE, 2, -1, null, null, null),
                new MoveRecord(275,1, MoveAction.TRADE_HIRE, 2, -1, null, null, null),
                new MoveRecord(276,2, MoveAction.END_TURN, -1, -1, null, null, null),
                new MoveRecord(277,0, MoveAction.TRADE_HIRE, 1, -1, null, null, null),
                new MoveRecord(278,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(279,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(280,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(281,2, MoveAction.REPEL, -1, -1, null, null, null),
                new MoveRecord(282,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(283,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(284,2, MoveAction.REPEL, -1, -1, null, null, null),
                new MoveRecord(285,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(286,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(287,2, MoveAction.REPEL, -1, -1, null, null, null),
                new MoveRecord(288,2, MoveAction.DISCOVER, null, null, null),
                new MoveRecord(289,2, MoveAction.FINISH_DISCOVER, null, null, null),
                new MoveRecord(290,2, MoveAction.TRADE_HIRE, 2, -1, null, null, null),
                new MoveRecord(291,0, MoveAction.TRADE_HIRE, 1, -1, null, null, null),
                new MoveRecord(292,1, MoveAction.TRADE_HIRE, 1, -1, null, null, null),
                new MoveRecord(293,0, MoveAction.FINISH_DISCOVER, null, null, null),
                new MoveRecord(294,0, MoveAction.END_TURN, -1, -1, null, null, null),
                new MoveRecord(295,1, MoveAction.COMMIT_EXPEDITION, 3, List.of(ExpeditionEmployee.CAPTAIN, ExpeditionEmployee.SETTLER, ExpeditionEmployee.CAPTAIN), null, null, null),
                new MoveRecord(296,1, MoveAction.COMMIT_EXPEDITION, 0, List.of(ExpeditionEmployee.CAPTAIN, ExpeditionEmployee.HANDYMAN), null, null, null),
                new MoveRecord(297,1, MoveAction.FINISH_DISCOVER, null, null, null),
                new MoveRecord(298,1, MoveAction.END_TURN, -1, -1, null, null, null),
                new MoveRecord(299,2, MoveAction.FINISH_DISCOVER, null, null, null),
                new MoveRecord(300,2, MoveAction.END_TURN, -1, -1, null, null, null)
        );
        IOFacade.saveMovesToCSV(moves, "IOFacadeMovesTest_output");
    }

    @Test
    public void testLoadMovesFromResourceCSV() throws IOGameException {
        List<MoveRecord> moves = IOFacade.loadMovesFromResourceCSV("IOFacadeMovesTest_input");
        assertThat(moves).isNotNull();
        assertThat(moves.size()).isEqualTo(7);
    }
}
